export const Products = [
    {   
        id: 1,
        name : "Risol",
        deskripsi : "(3pcs Rp 5.000)",
        img : "https://res.cloudinary.com/dfcpydoq8/image/upload/v1715497216/gorengan_xoeds9.png",
        price : "5000",
        category : "gorengan",
        status: "Tersedia",
        // status: "Habis",
    },
    {   
        id : 2,
        name : "Tahu Isi",
        deskripsi : "(3pcs Rp 5.000)",
        img : "https://res.cloudinary.com/dfcpydoq8/image/upload/v1715497216/gorengan_xoeds9.png",
        price : "5000",
        category: "gorengan",
        status: "Tersedia",
        // status: "Habis"
    },
    {   
        id : 3,
        name : "Bakwan",
        deskripsi : "(3pcs Rp 5.000)",
        img : "https://res.cloudinary.com/dfcpydoq8/image/upload/v1715497216/gorengan_xoeds9.png",
        price : "5000",
        category: "gorengan",
        status: "Tersedia",
        // status: "Habis",
    },
    {   
        id : 4,
        name : "Pisang Goreng",
        deskripsi : "(3pcs Rp 5.000)",
        img : "https://res.cloudinary.com/dfcpydoq8/image/upload/v1715497216/gorengan_xoeds9.png",
        price : "5000",
        category: "gorengan",
        status: "Tersedia",
        // status: "Habis",
    },
    // {   
    //     id : 4,
    //     name : "Dadar",
    //     deskripsi : "(3pcs Rp 5.000)",
    //     img : "https://res.cloudinary.com/dfcpydoq8/image/upload/v1716120072/dadar_kfp9js.jpg",
    //     price : "5000",
    //     category: "gorengan",
    //     // status: "Tersedia",
    //     status: "Habis",
    // },
    {   
        id : 5,
        name : "Gorengan campur",
        deskripsi : "(3pcs Rp 5.000)",
        img : "https://res.cloudinary.com/dfcpydoq8/image/upload/v1715497216/gorengan_xoeds9.png",
        price : "5000",
        category: "gorengan",
        status: "Tersedia",
        // status: "Habis"
    },
]